export const reporteSasColumns = [
  { field: 'nroOT', header: 'N° OT', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '82px', type: 'text' },
  { field: 'estadoOT', header: 'Estado', hidden: false, exportable: true, filter: true, sort: true, width: '120px', minWidth: '90px', type: 'text' },
  { field: 'gestionada', header: 'Gestionada', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '90px', type: 'text' },
  { field: 'codTarea', header: 'Código Tarea', hidden: false, exportable: true, filter: true, sort: true, width: '118px', minWidth: '96px', type: 'text' },
  { field: 'localidad', header: 'Localidad', hidden: false, exportable: true, filter: true, sort: true, width: '128px', minWidth: '96px', type: 'text' },
  { field: 'codPostal', header: 'Código Postal', hidden: false, exportable: true, filter: true, sort: true, width: '118px', minWidth: '96px', type: 'text' },
  { field: 'legajoOperadorDescarga', header: 'Legajo Operador Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '170px', minWidth: '140px', type: 'text' },
  { field: 'nomApeOperadorDescarga', header: 'Nombre Operador Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '210px', minWidth: '160px', type: 'text' },
  { field: 'fechaDescarga', header: 'Fecha Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '150px', minWidth: '125px', type: 'text' },
  { field: 'legajoNOLDAP', header: 'Legajo NOLDAP', hidden: false, exportable: false, filter: true, sort: true, width: '310px', minWidth: '240px', type: 'legajoList' },
  { field: 'fechaCierreOT', header: 'Fecha Cierre OT', hidden: false, exportable: true, filter: true, sort: true, width: '150px', minWidth: '125px', type: 'text' },
  { field: 'centro', header: 'Centro', hidden: false, exportable: true, filter: true, sort: true, width: '95px', minWidth: '80px', type: 'text' },
  { field: 'almacen', header: 'Almacén', hidden: false, exportable: true, filter: true, sort: true, width: '95px', minWidth: '80px', type: 'text' },
  { field: 'serialCodMaterial', header: 'Serial Cod Material', hidden: false, exportable: true, filter: true, sort: true, width: '160px', minWidth: '125px', type: 'text' },
  { field: 'descMaterial', header: 'Material', hidden: false, exportable: true, filter: true, sort: true, width: '150px', minWidth: '120px', type: 'text' },
  { field: 'cantidadMaterial', header: 'Cantidad', hidden: false, exportable: true, filter: true, sort: true, width: '95px', minWidth: '80px', type: 'text' },
  { field: 'tipoDescarga', header: 'Tipo Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '130px', minWidth: '105px', type: 'text' },
  { field: 'mensajeSAP', header: 'Mensaje SAP', hidden: false, exportable: true, filter: true, sort: true, width: '260px', minWidth: '180px', type: 'text' },
  { field: 'fechaNotificacionSAP', header: 'Fecha Notificación SAP', hidden: false, exportable: true, filter: true, sort: true, width: '170px', minWidth: '135px', type: 'text' }
];
