export const reporteSasColumns = [
  { field: 'nroOT', header: 'N° OT', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '64px', type: 'text' },
  { field: 'estadoOT', header: 'Estado', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '70px', type: 'text' },
  { field: 'gestionada', header: 'Gestionada', hidden: false, exportable: true, filter: true, sort: true, width: '104px', minWidth: '70px', type: 'text' },
  { field: 'codTarea', header: 'Código Tarea', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '72px', type: 'text' },
  { field: 'localidad', header: 'Localidad', hidden: false, exportable: true, filter: true, sort: true, width: '118px', minWidth: '72px', type: 'text' },
  { field: 'codPostal', header: 'Código Postal', hidden: false, exportable: true, filter: true, sort: true, width: '108px', minWidth: '72px', type: 'text' },
  { field: 'legajoOperadorDescarga', header: 'Legajo Operador Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '158px', minWidth: '86px', type: 'text' },
  { field: 'nomApeOperadorDescarga', header: 'Nombre Operador Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '205px', minWidth: '110px', type: 'text' },
  { field: 'fechaDescarga', header: 'Fecha Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '146px', minWidth: '92px', type: 'text' },
  { field: 'legajoNOLDAP', header: 'Legajo NOLDAP', hidden: false, exportable: false, filter: true, sort: true, width: '245px', minWidth: '120px', type: 'legajoList' },
  { field: 'fechaCierreOT', header: 'Fecha Cierre OT', hidden: false, exportable: true, filter: true, sort: true, width: '146px', minWidth: '92px', type: 'text' },
  { field: 'centro', header: 'Centro', hidden: false, exportable: true, filter: true, sort: true, width: '88px', minWidth: '58px', type: 'text' },
  { field: 'almacen', header: 'Almacén', hidden: false, exportable: true, filter: true, sort: true, width: '88px', minWidth: '58px', type: 'text' },
  { field: 'serialCodMaterial', header: 'Serial Cod Material', hidden: false, exportable: true, filter: true, sort: true, width: '150px', minWidth: '92px', type: 'text' },
  { field: 'descMaterial', header: 'Material', hidden: false, exportable: true, filter: true, sort: true, width: '146px', minWidth: '86px', type: 'text' },
  { field: 'cantidadMaterial', header: 'Cantidad', hidden: false, exportable: true, filter: true, sort: true, width: '88px', minWidth: '58px', type: 'text' },
  { field: 'tipoDescarga', header: 'Tipo Descarga', hidden: false, exportable: true, filter: true, sort: true, width: '122px', minWidth: '78px', type: 'text' },
  { field: 'mensajeSAP', header: 'Mensaje SAP', hidden: false, exportable: true, filter: true, sort: true, width: '235px', minWidth: '100px', type: 'text' },
  { field: 'fechaNotificacionSAP', header: 'Fecha Notificación SAP', hidden: false, exportable: true, filter: true, sort: true, width: '162px', minWidth: '96px', type: 'text' }
];
