export const reporteSasColumns = [
  { field: 'nroOT', header: 'N° OT', filter: true },
  { field: 'estadoOT', header: 'Estado', filter: true },
  { field: 'gestionada', header: 'Gestionada', filter: true },
  { field: 'codTarea', header: 'Código Tarea', filter: true },
  { field: 'localidad', header: 'Localidad', filter: true },
  { field: 'codPostal', header: 'Código Postal', filter: true },
  { field: 'legajoOperadorDescarga', header: 'Legajo Operador Descarga', filter: true },
  { field: 'nomApeOperadorDescarga', header: 'Nombre Operador Descarga', filter: true },
  { field: 'fechaDescarga', header: 'Fecha Descarga', filter: true },
  { field: 'legajoNOLDAP', header: 'Legajo NOLDAP', filter: true, exportable: false },
  { field: 'fechaCierreOT', header: 'Fecha Cierre OT', filter: true },
  { field: 'centro', header: 'Centro', filter: true },
  { field: 'almacen', header: 'Almacén', filter: true },
  { field: 'serialCodMaterial', header: 'Serial Cod Material', filter: true },
  { field: 'descMaterial', header: 'Material', filter: true },
  { field: 'cantidadMaterial', header: 'Cantidad', filter: true },
  { field: 'tipoDescarga', header: 'Tipo Descarga', filter: true },
  { field: 'mensajeSAP', header: 'Mensaje SAP', filter: true },
  { field: 'fechaNotificacionSAP', header: 'Fecha Notificación SAP', filter: true },
];