export const columns = [
  { field: 'id', header: 'ID OT FALLIDAS', hidden: true, exportable: false, filter: false, sort: false },
  { field: 'nroOrdenTrabajo', header: 'NRO. OT', hidden: false, exportable: true, filter: true, sort: true, width: '120px' },
  { field: 'fechaCierre', header: 'FECHA CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '140px' },
  { field: 'tareaCodigo', header: 'COD TAREA', hidden: false, exportable: true, filter: true, sort: true, width: '110px' },
  { field: 'direccion', header: 'DIRECCION', hidden: false, exportable: true, filter: true, sort: true, width: '150px' },
  { field: 'ciudad', header: 'CIUDAD', hidden: false, exportable: true, filter: true, sort: true, width: '125px' },
  { field: 'provincia', header: 'PROVINCIA', hidden: false, exportable: true, filter: true, sort: true, width: '130px' },
  { field: 'region', header: 'REGION', hidden: false, exportable: true, filter: true, sort: true, width: '110px' },
  { field: 'pais', header: 'PAIS', hidden: false, exportable: true, filter: true, sort: true, width: '90px' },
  { field: 'contratista', header: 'CONTRATISTA', hidden: false, exportable: true, filter: true, sort: true, width: '160px' },
  { field: 'tecnicoCierre', header: 'TECNICO CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '130px' },
  { field: 'actividades', header: 'ACTIVIDADES', hidden: false, exportable: true, filter: true, sort: true, width: '160px' },
  { field: 'sistemaOrigen', header: 'SISTEMA ORIGEN', hidden: false, exportable: true, filter: true, sort: true, width: '130px' },
  { field: 'errorDescripcion', header: 'DESCRIPCION ERROR', hidden: false, exportable: true, filter: true, sort: true, width: '180px' },
  { field: 'excluida', header: 'EXCLUIDA', hidden: false, exportable: true, filter: true, sort: true, width: '100px' },
  { field: 'motivoExclusion', header: 'MOTIVO EXCLUSION', hidden: false, exportable: true, filter: true, sort: true, width: '170px' },
  { field: 'nota', header: 'NOTA', hidden: true, exportable: true, filter: false, sort: false },
  { field: 'tieneNota', header: 'NOTA', hidden: false, exportable: false, filter: false, sort: false, width: '90px' },
  { field: 'incluirExp', header: 'INCLUIR', hidden: true, exportable: true, filter: false, sort: false },
  { field: 'incluir', header: 'INCLUIR', hidden: false, exportable: false, filter: false, sort: false, width: '90px' }
]
