export const columns = [
  { field: 'id', header: 'ID OT FALLIDAS', hidden: true, exportable: false, filter: false, sort: false },
  { field: 'nroOrdenTrabajo', header: 'NRO. OT', hidden: false, exportable: true, filter: true, sort: true, width: '132px', minWidth: '72px', type: 'text' },
  { field: 'fechaCierre', header: 'FECHA CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '135px', minWidth: '92px', type: 'text' },
  { field: 'tareaCodigo', header: 'COD TAREA', hidden: false, exportable: true, filter: true, sort: true, width: '105px', minWidth: '76px', type: 'text' },
  { field: 'direccion', header: 'DIRECCION', hidden: false, exportable: true, filter: true, sort: true, width: '168px', minWidth: '96px', type: 'text' },
  { field: 'ciudad', header: 'CIUDAD', hidden: false, exportable: true, filter: true, sort: true, width: '120px', minWidth: '86px', type: 'text' },
  { field: 'provincia', header: 'PROVINCIA', hidden: false, exportable: true, filter: true, sort: true, width: '128px', minWidth: '88px', type: 'text' },
  { field: 'region', header: 'REGION', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '72px', type: 'text' },
  { field: 'pais', header: 'PAIS', hidden: false, exportable: true, filter: true, sort: true, width: '78px', minWidth: '58px', type: 'text' },
  { field: 'contratista', header: 'CONTRATISTA', hidden: false, exportable: true, filter: true, sort: true, width: '172px', minWidth: '105px', type: 'text' },
  { field: 'tecnicoCierre', header: 'TECNICO CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '132px', minWidth: '92px', type: 'text' },
  { field: 'actividades', header: 'ACTIVIDADES', hidden: false, exportable: true, filter: true, sort: true, width: '174px', minWidth: '105px', type: 'text' },
  { field: 'sistemaOrigen', header: 'SISTEMA ORIGEN', hidden: false, exportable: true, filter: true, sort: true, width: '132px', minWidth: '92px', type: 'text' },
  { field: 'errorDescripcion', header: 'DESCRIPCION ERROR', hidden: false, exportable: true, filter: true, sort: true, width: '180px', minWidth: '115px', type: 'text' },
  { field: 'excluida', header: 'EXCLUIDA', hidden: false, exportable: true, filter: true, sort: true, width: '104px', minWidth: '72px', type: 'text' },
  { field: 'motivoExclusion', header: 'MOTIVO_EXCLUSION', hidden: false, exportable: true, filter: true, sort: true, width: '174px', minWidth: '115px', type: 'text' },
  { field: 'nota', header: 'NOTA', hidden: true, exportable: true, filter: false, sort: false, type: 'exportText' },
  { field: 'tieneNota', header: 'NOTA', hidden: false, exportable: false, filter: false, sort: false, width: '82px', minWidth: '62px', type: 'action', action: 'nota', icon: 'pi pi-file-edit', buttonClass: 'fm-icon-btn', title: 'Editar nota', ariaLabel: 'Editar nota' },
  { field: 'incluirExp', header: 'INCLUIR', hidden: true, exportable: true, filter: false, sort: false, type: 'exportText' },
  { field: 'incluir', header: 'INCLUIR', hidden: false, exportable: false, filter: false, sort: false, width: '84px', minWidth: '62px', type: 'action', action: 'incluir', icon: 'pi pi-replay', buttonClass: 'fm-icon-btn', title: 'Recuperar OT', ariaLabel: 'Recuperar OT', showWhenField: 'excluida', showWhenValue: 'S' }
]
